baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Mysticetus"

# assetDir = "static/img"

googleAnalytics = ""

ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[[menu.main]]
  name = "Industries"
  url = "/industry/"
  weight = 1
  identifier = "industry"
[[menu.main]]
  name = "Energy"
  url = "/industry/energy/"
  weight = 1
  parent = "industry"
[[menu.main]]
  name = "PSO Providers"
  url = "/industry/pso-provider/"
  weight = 2
  parent = "industry"
[[menu.main]]
  name = "Academia"
  url = "/industry/academia/"
  weight = 3
  parent = "industry"

[[menu.main]]
  name = "Tech Services"
  url = "/product/"
  weight = 2
	identifier = "product"

[[menu.main]]
	name = "Mysticetus"
	weight = 3
	identifier = "mysticetus_features"
[[menu.main]]
	name = "Automatic Reporting"
	url = "/feature/reporting/"
	weight = 1
	parent = "mysticetus_features"
[[menu.main]]
	name = "Data Collection"
	url = "/feature/data-collection/"
	weight = 1
	parent = "mysticetus_features"
[[menu.main]]
	name = "Data Driven Mitigation"
	url = "/feature/mitigation/"
	weight = 1
	parent = "mysticetus_features"
[[menu.main]]
	name = "Downloads"
	url = "/download/"
	weight = 1
	parent = "mysticetus_features"

[[menu.main]]
  name = "Company"
  url = "/company/"
  weight = 4
	identifier = "company"
[[menu.main]]
  name = "About"
  url = "/company/about/"
  weight = 1
  parent = "company"
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 2
  parent = "company"

# [[menu.main]]
#   name = "Pricing"
#   url = "/pricing/"
#   weight = 4

[[menu.footer]]
	identifier = "mysticetus"
	name = "Mysticetus"
	weight = 1
[[menu.footer]]
	name = "Energy"
	url = "/industry/energy/"
	weight = 1
	parent = "mysticetus"
[[menu.footer]]
	name = "PSO Providers"
	url = "/industry/pso-provider/"
	weight = 2
	parent = "mysticetus"
[[menu.footer]]
	name = "Academia"
	url = "/industry/academia/"
	weight = 3
	parent = "mysticetus"
[[menu.footer]]
	name = "Tech Services"
	url = "/product/"
	weight = 4
	parent = "mysticetus"
[[menu.footer]]
	name = "----"
	weight = 5
	parent= "mysticetus"
[[menu.footer]]
	name = "Request a Demo"
	url = "/demo/"
	weight = 6
	parent = "mysticetus"
# [[menu.footer]]
# 	name = "Pricing"
# 	url = "/pricing/"
# 	weight = 5
# 	parent = "mysticetus"

[[menu.footer]]
	identifier = "features"
	name = "Features"
	weight = 2
[[menu.footer]]
	name = "Automatic Reporting"
	url = "/feature/reporting/"
	weight = 1
	parent = "features"
[[menu.footer]]
	name = "Data Collection"
	url = "/feature/data-collection/"
	weight = 1
	parent = "features"
[[menu.footer]]
	name = "Data Driven Mitigation"
	url = "/feature/mitigation/"
	weight = 1
	parent = "features"


[[menu.footer]]
	identifier = "company"
	name = "Company"
	weight = 3
[[menu.footer]]
	name = "About"
	url = "/company/about/"
	weight = 1
	parent = "company"
[[menu.footer]]
	name="Help"
	url = "/contact/"
	weight = 2
	parent = "company"
[[menu.footer]]
	name = "Contact"
	url = "/contact/"
	weight = 3
	parent = "company"
# [[menu.footer]]
# 	name="Privacy"
# 	url = "/privacy/"
# 	weight = 2
# 	parent = "company"
# [[menu.footer]]
# 	name="Terms & Use"
# 	url = "/terms/"
# 	weight = 3
# 	parent = "company"
# [[menu.footer]]
# 	name="Security"
# 	url = "/security/"
# 	weight = 4
# 	parent = "company"

[taxonomy]
	industry = "industry"

[params]
	logo = "/img/mysticetus.png"
	fullName = "Mysticetus, LLC."
	cta_text = "Request a Demo"
	footerLogo = "/img/mysticetus.png"
	footerText = "Changing the way teams observe, protect, and manage Anthropogenic operations near protected marine wildlife."
